# Generated by Django 5.1.1 on 2024-09-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_patient_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cleaning', 'Cleaning'), ('Filling', 'Filling'), ('Root Canal', 'Root Canal'), ('Crown', 'Crown'), ('Teeth Whitening', 'Teeth Whitening')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='office_address',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='npi',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(related_name='doctors', to='staff_patient_management.specialty'),
        ),
    ]
