# Generated by Django 5.1.1 on 2024-09-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_patient_management', '0002_specialty_remove_doctor_office_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialties',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
